databases:
  - name: sample_app_db
    databaseName: sample_app_db
    user: sample_app
    region: singapore

services:
  - type: web
    name: sample_app
    env: docker
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:sample_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false